Разметка главной страницы
htmlacademy-htmlcss/2011595-sedona-33 pull request #2
Opened 2022-01-23 15:32 UTC by slava560730

2022-01-23 18:50 UTC, Manyaka requested changes

2022-01-23 18:50 UTC, Manyaka commented on Catalog.html
> +<!DOCTYPE html>
catalog - c маленькой буквы

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +        <img class="page-header-logo" alt="Логотип Седона" src="">
```suggestion
        <img class="page-header-logo" alt="Логотип Седона." src="">
```

в альтах ставим точки, для интонационной паузы, чтобы скрин-ридер сделал остановку - можешь в инете почитать по-подробнее зачем. Или, если интересно, я могу надиктовать ответ в телеге

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +          <a class="navigation-link navigation-link-current" href="#">Главная</a>
```suggestion
          <a class="navigation-link navigation-link-current">Главная</a>
``

раз мы уже на главной - хреф не нужен

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +            <span class="visually-hidden">Поиск</span>
```suggestion
            <span class="visually-hidden">Поиск.</span>
```

и во всех вижуали-хидден элементах ставим точку, аналогично альтам

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +              Favorite
русский язык - мы на русском сайте. А почему мы на русском сайте?  Какой атрибут нам говорит, что мы на русском сайте, на котором язык - русский?

и точка

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +          <button class="header-button">Хочу сюда</button>
```suggestion
          <button class="header-button" type="button">Хочу сюда</button>
```

что происходит, когда не пишешь атрибут?

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +    </h1>
h1 мы никогда не делаем скрытым, чтобы сеошники нас не побили. Тебе тут вообще зачем этот элемент?

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +    <img class="logo" src="" alt="Логотип Великолепная Седона">
точки в альтах. Ну и многовато логотипов, придумай другие альты

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +-->
ну на самом деле это бекграунд и свг картинка, т.е там img в единственном числе

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +        Преимущества
отсюда и везде поставь точки в вижуали-хидден,  я больше к ним коменты не буду писать, чтобы не писать одно и тоже

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +      <h2 class="advantage-intro">СЕДОНА - НЕБОЛЬШОЙ ГОРОДОК В АРИЗОНЕ, <br> ЗАСЛУЖИВАЮЩИЙ БОЛЬШЕГО!</h2>
как тебе такой вариант: это h1 заголовок? как ты думаешь, он подходит?

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +        <span class="advantage-nomber">
```suggestion
        <span class="advantage-number">
```

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +      </div>
картинку можно включить в предыдущий див

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +      </div>
ну и я дальше не буду писать: точки в альтах, и вообще, было бы идеально, если бы ты придумал нормальные описания, но я не помню, будет ли ещё домашка по доступности, в которой ты это всё будешь переделывать, можно сразу хорошо сделать :)

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +      </div>
тут по аналогии с первым - они все помещаются в один див

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +          <span class="advantage-nomber">
```suggestion
          <span class="advantage-number">
```

если я там пропустила, везде намберы поправь :) Номбер - это вроде "человек" на итальянском. Звучит похоже, по крайней мере :)

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +      </div>
это бекграунд, поэтому img не нужен

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +    <section class="footer-social">
секшен есть, должен быть заголовок у секции

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +    <section class="footer-social">
а вообще она лишняя, уже есть структурирующий элемент ul

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +    </pre>
нет, конечно, это не pre, потому что на боевых сайтах никогда не используется pre. Это свг картинка. Более того, она со ссылкой, чтобы можно было перейти на сайт академии, как написано на странице требований:
https://www.figma.com/file/QhPyqbohrpaAaz9qCkJhE6/HTML-1-%2F-%D0%A1%D0%B5%D0%B4%D0%BE%D0%BD%D0%B0?node-id=305%3A2

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +    </pre>
но задумка хорошая :)

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +    </section>
опять, слишком мелкий блок, чтобы использовать секцию. Ну и это телефон - его надо оформить как телефон, а не как заголовок

2022-01-23 18:50 UTC, Manyaka commented on index.html
> +    <section class="footer-html-academy">
и это не секция

2022-01-24 15:25 UTC, slava560730 commented on index.html
> +              Favorite
<html lang="ru">

2022-01-24 15:45 UTC, slava560730 commented on index.html
> +          <button class="header-button">Хочу сюда</button>
по умолчанию type="submit" - отправка на сервер
поэтому нужно указывать type="button"

2022-01-24 16:00 UTC, slava560730 commented on index.html
> +    </h1>
Для разметки названия основной страницы
в лайве№2 таймкод 1:27:00 тоже скрывают h1
+ в материалах где то была инфа по этому поводу, кажется...
но я убрал Ок

2022-01-24 16:13 UTC, slava560730 commented on index.html
> +    </h1>
по поводу структуры наверно больше подходит другой заголовок, который ниже
но по поводу <h1 class="visually-hidden"> получается в лайве неправильно сказали?

2022-01-24 16:25 UTC, slava560730 commented on index.html
> +      </div>
> картинку можно включить в предыдущий див
Там дальше для аналогичного второго изображения есть такая же картинка:
<div class="advantage-pic-second">
        <img src="" alt="Фотография моста Дьявола.">
      </div>
Я предполагал что нужно каждой картинке задать свой класс для гибкой настройки расположения и редактирования(сложно предположить как все это будет реализовываться в css по классам)
Включу в соседние дивы

2022-01-24 16:27 UTC, slava560730 commented on index.html
> +      </div>
<code>
<div class="advantage-pic-second">
        <img src="" alt="Фотография моста Дьявола.">
      </div>
      </code>

2022-01-24 16:27 UTC, slava560730 commented on index.html
> +      </div>
почему я не могу вставить строчку кода в <code></code>?;)

2022-01-24 16:28 UTC, slava560730 commented on index.html
> +      </div>
<co de><co de>

2022-01-24 16:28 UTC, slava560730 commented on index.html
> +      </div>
code></code

2022-01-24 16:40 UTC, slava560730 commented on index.html
> +      </div>
upd:
прочитал следующий комент
захотел стереть часть комента выше на счет упоминания "аналогичного второго изображения", но теперь интересно как вставить сюда строчку кода

2022-01-24 16:43 UTC, slava560730 commented on index.html
> +      </div>
> ну и я дальше не буду писать: точки в альтах, и вообще, было бы идеально, если бы ты придумал нормальные описания, но я не помню, будет ли ещё домашка по доступности, в которой ты это всё будешь переделывать, можно сразу хорошо сделать :)

Нормальные описания...? Дело в более глубоком описании? точнее описывать нужно всм?

2022-01-24 16:47 UTC, slava560730 commented on index.html
> +      </div>
по поводу 114 строчки понял и исправил
а вот то что до неё
Зачем помещать список в div(или что имеется ввиду)? там же и заголовок и абзац помимо иконки в каждой строчке {li> списка.
у меня нет правильного представления видимо зачем мы делаем именно такую структуру классов и как будем с ними работать

2022-01-24 16:50 UTC, slava560730 commented on index.html
> +      </div>
Соответственно удалил все бекграунды 
в начале тоже есть перед h1

2022-01-24 16:56 UTC, slava560730 commented on index.html
> +    <section class="footer-social">
В этом случае решил добавить заголовок "Наши социальные сети" для структуры разметки страницы

2022-01-25 18:19 UTC, Manyaka commented on index.html
> +          <button class="header-button">Хочу сюда</button>
точно

2022-01-25 18:29 UTC, Manyaka commented on index.html
> +      </div>
да, ты каждой картинке сделаешь свой класс, где нужно будет. Для этого картинки можно в див не оборачивать, а сделать `<img class="image-class">`

2022-01-25 19:01 UTC, Manyaka requested changes

2022-01-25 19:18 UTC, Manyaka commented on index.html
> +      <button class="btn-search" type="button">Поиск гостиницы в Седоне</button>
Хорошо, что указал тип кнопки!

2022-01-25 19:19 UTC, merged