Разметка каталога
htmlacademy-htmlcss/2011595-sedona-33 pull request #3
Opened 2022-01-26 07:22 UTC by slava560730

2022-01-26 07:34 UTC, Manyaka commented on index.html
> +    </label>
Надо подравнять, и я тормознула, потому что, хотя и можно инпут обернуть в лейбл, но так мало кто делает, поэтому чето не обратила внимание, что у лейбла у тебя класс visually-hidden, а это значит, что весь инпут будет скрыт. Не надо так. Лейбл связывается с инпутом через id.

2022-01-27 16:04 UTC, Manyaka requested changes

2022-01-28 18:05 UTC, slava560730 commented on catalog.html
> +          <a class="navigation-link" href="catalog.html">Гостиницы</a>
Видимо я запутался немного, когда удалял каталог из корня
потому что я точно это убирал...

2022-01-28 18:13 UTC, slava560730 commented on catalog.html
> +        <img src="" alt="Разработано HTML академией."></a>
Классная возможность
сделал

2022-01-28 18:41 UTC, slava560730 commented on catalog.html
> +        ЗАГРУЗИ ЕЩЁ
Я длинный текст копирую
короткий лень было прокликивать...

2022-01-29 10:43 UTC, Manyaka commented on catalog.html
> +    <section class="distribution">
не сделано

2022-01-29 10:51 UTC, Manyaka commented on catalog.html
> +              Аппартаменты
```suggestion
              Апартаменты
```

2022-01-29 10:51 UTC, Manyaka commented on catalog.html
> +        <img src="" alt="Разработано HTML академией."></a>
не сделано

2022-01-29 11:17 UTC, Manyaka requested changes

2022-01-29 11:17 UTC, Manyaka commented on catalog.html
> +        <option value="expensive">Сначала дорогое</option>
проверь текстовки

2022-01-29 11:17 UTC, Manyaka commented on catalog.html
> +      <select class="select-control" aria-label="Сортировка">
```suggestion
      <select class="select-control" aria-label="Отсортировать гостиницы как:">
```

да, можно использовать aria-label вместо лейбла, единственный минус - он не переводится автопереводчиками, а так норм :) Отлично придумал!

2022-01-29 11:17 UTC, Manyaka commented on catalog.html
> +      </a>
оптимально, если бы добавил слово "гостиниц", типа "Показать карточки гостиниц", хотя, конечно, мы в контексте страницы, тут я лично по себе сужу, тк у меня слуховая память не очень, и я сразу забываю :)))

2022-01-29 11:17 UTC, Manyaka commented on catalog.html
> +        <select class="select-control" aria-label="Число гостиниц на странице:">
```suggestion
        <select class="select-control" aria-label="показать число гостиниц на странице:">
```

2022-01-29 11:17 UTC, Manyaka commented on catalog.html
> +          Ваш e-mail. </label>
ну вот пример неудачного бьютифая, когда ты не понимаешь, где начало, а где конец тега. Лучше такое или самому руками тогда править, или может там надо бьютифай донастроить, там у него опции есть.

2022-01-29 12:57 UTC, slava560730 commented on catalog.html
> +          </fieldset>
Оставил на потом

2022-01-29 13:45 UTC, merged